# This file stores configurations for your Shopify app.

scopes = "write_products, read_metaobjects, read_metaobject_definitions, write_metaobject_definitions, write_metaobjects, read_content, write_content"